---
# -- (Optional) When using a custom network
# networks:
#   your-custom-network:
#     -- (Optional) When attaching an external network
#     external: true
services:
  twingate_connector:
    container_name: twingate_connector
    image: docker.io/twingate/connector:1.73.0
    environment:
      - TWINGATE_NETWORK=bandwithbros
      - TWINGATE_ACCESS_TOKEN=$eyJhbGciOiJFUzI1NiIsImtpZCI6IkRWV2VZTk5sV0ZqYl9mdHNFZWRBZjF0b1VxblRDUnhaeS1seXpVSFRCOHciLCJ0eXAiOiJEQVQifQ.eyJudCI6IkFOIiwiYWlkIjoiNDExMjY4IiwiZGlkIjoiMTg4NDMxNyIsImp0aSI6ImRiNTRhZTZkLTBiMGUtNDQ4Mi1iYTdkLTE5NjgwOGQ4MTYyZSIsImlzcyI6InR3aW5nYXRlIiwiYXVkIjoiYmFuZHdpdGhicm9zIiwiZXhwIjoxNzM1OTMzMDA2LCJpYXQiOjE3MzU5Mjk0MDYsInZlciI6IjQiLCJ0aWQiOiIxMjE1MTQiLCJybnciOjE3MzU5Mjk3NTAsInJuZXRpZCI6IjE1OTc0MyJ9.vn0a5wXSCTsLZPyisTnHo4pT7aIjyfUMtBERs3pVQofXDNRop_e-Q11kDE6DAJrxer2q567EXv2ZxKVeJrrGZg
      - TWINGATE_REFRESH_TOKEN=$ET-oxBDDGZwp4lM5WZBE3q4fK-oSzXeJ7hAPgVAzyr86u0kPBI9so-Zg924sQs0EcV7WWnWKIkC6Lkq-eDJL05-PcFB6RssFJ7TlqJfPU1nHvg6odrdC4tbBOzXxEKGoiDHWJQ
      # -- (Optional) Change loglevel
      # - TWINGATE_LOG_LEVEL=3
      # -- (Optional) Add custom DNS Server
      # - TWINGATE_DNS=10.20.0.1
    sysctls:
      net.ipv4.ping_group_range: "0 2147483647"
    # -- (Optional) When using a custom network
    # networks:
    #   - your-custom-network
    restart: unless-stopped
